apiVersion: 1
datasources:
  - name: InfluxDB
    uid: influx-flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: ${INFLUX_ORG}
      defaultBucket: ${INFLUX_BUCKET_RAW}
    secureJsonData:
      token: ${INFLUX_TOKEN}
