; Kiem soat ra vao 2 lop (the + mat) - ESP32-S3 DevKitC-1, chay tren Wokwi for VS Code
; Build: pio run  ->  Wokwi: Start Simulator (doc wokwi.toml + diagram.json)

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit GFX Library@^1.11.11
    adafruit/Adafruit SSD1306@^2.5.13
    chris--a/Keypad@^3.1.1
    bblanchon/ArduinoJson@^7.2.1
